### PR TITLE
fix: sanitise placeholder inputs

### LINKED ISSUE #1354: Placeholder substitution may fail when replacement variables contain % sequences
### Describe the bug
Yep. This bug existed all the way back in Quaver 3.0.0
When some of the replacement variables contain special characters, especially % signs (as part of URL-encoded content), can accidentally resemble the placeholder syntax (like %1, %2, etc.)

https://github.com/ZPTXDev/Quaver/commit/50dd67a92bbbaac66f369fcfcbb367f761faa75b

If any replacement string (v) contains percent-encoded sequences, such as URLs with %2F, %20, etc/., cam cause some replacements to get skipped or misaligned.

Relevant code in question:
https://github.com/ZPTXDev/Quaver/blob/664127bd9ea65468b604fe583d3124b3ef62b1e0/src/lib/util/util.ts#L74

```js
vars.forEach((v, i): string => localeString = localeString.replace(`%${i + 1}`, v))
```

### Severity

Low

### Affected branches

- [x] Stable
- [x] Next

### Quaver version

`>=3.0.0-next.10`

### Steps to reproduce

Pass a string on `v` with percent-encoded sequences:

Such as `https://zptx.dev/%1%2%3%4`

```js
export function getLocaleString(
    localeCode: string,
    stringPath: string,
    ...vars: string[]
): string | 'LOCALE_MISSING' {
    if (!locales.get(localeCode)) return 'LOCALE_MISSING';
    let strings = locales.get(localeCode);
    let localeString: string = get(strings, stringPath);
    if (!localeString) {
        // This uses 'en' on purpose.
        // 'en' is the only locale with a guaranteed 100% completion rate.
        strings = locales.get('en');
        localeString = get(strings, stringPath);
    }
    if (!localeString) return stringPath;
    vars.forEach(
        (v, i): string => (localeString = localeString.replace(`%${i + 1}`, v)),
    );
    return localeString;
}
```

### Expected behavior

Correctly parse the string.

### Actual behavior

Some of Quaver's behavior that utilizes that function may involve URIs that contains those characters such as when `/move`-ing a track.

### Relevant log output

```shell
n/a
```

### PR DESCRIPTION
**Pull request by zapteryx**
### Thank you for your interest in contributing!
Before proceeding, please review the [guidelines for contributing](https://github.com/ZPTXDev/Quaver/blob/master/CONTRIBUTING.md).

- [x] Are you targeting the `next` branch? (left side)
- [x] Did you review the guidelines for contributing?
- [x] Does your code pass linting checks?
- [x] Is your code documented, if applicable? (Check if not applicable)
- [x] Does this PR have a linked issue?

### Scope of change
- [ ] Major change
- [x] Minor change
- [ ] Documentation only

### Type of change
- [x] Bug fix
- [ ] Feature
- [ ] Other

### Priority
- [ ] Critical
- [x] High
- [ ] Medium
- [ ] Low

### Description
Please describe the changes.
Fixes lack of placeholder input sanitisation, using encodeURI and escapeMarkdown (from d.js) to sanitise strings
Fixes #1354 as a result

### CODE REVIEW

**Comment by zapteryx** [comment]
@xayanide require your testing, ty

File: src/lib/util/util.ts [hunk 1]
```diff
@@ -66,10 +66,11 @@ export function getLocaleString(
...
     if (!localeString) return stringPath;
-    vars.forEach(
-        (v, i): string => (localeString = localeString.replace(`%${i + 1}`, v)),
-    );
-    return localeString;
+    const safeVars = vars.map((v): string => encodeURI(escapeMarkdown(v)));
+    safeVars.forEach((v, i): void => {
+        localeString = localeString.replace(`%${i + 1}`, v);
+    });
+    return decodeURI(localeString);
```
Comment (xayanide) [inline src/lib/util/util.ts:73]: Current test result:
Playing a youtube playlist crashes it. Howerver, youtube links work fine.
In the logs, you'll see the inputs before it gets decoded so you can see how it crashed.

```js
2025-04-11T11:49:41.764Z  INFO  Quaver [G 906471497231630336 | U 250934589621665793] Processing chatInputCommands commandName: play query: https://www.youtube.com/playlist?list=PL8lZieNFgOdmrNGTqwjqYJpJ_2nw_O_M2
2025-04-11T11:49:42.225Z  INFO  Quaver [G 906471497231630336 | U 250934589621665793] Executing chatInputCommands commandName: play query: https://www.youtube.com/playlist?list=PL8lZieNFgOdmrNGTqwjqYJpJ_2nw_O_M2
Safe vars: [
  '324',
  'Best%20anime%20songs%20playlist',
  'https://www.youtube.com/playlist?list=PL8lZieNFgOdmrNGTqwjqYJpJ_2nw_O_M2'
]
localeString: Added **324** tracks from [**Best%20anime%20songs%20playlist**](https://www.youtube.com/playlist?list=PL8lZieNFgOdmrNGTqwjqYJpJ_2nw_O_M2) to queue
2025-04-11T11:49:46.645Z  INFO  Quaver [G 906471497231630336] Starting track
Safe vars: [
  "God%20knows...%20''The%20Melancholy%20of%20Haruhi%20Suzumiya''%20%E3%80%90%E6%B6%BC%E5%AE%AE%E3%83%8F%E3%83%AB%E3%83%92%E3%81%AE%E6%86%82%E9%AC%B1%E3%80%91Kadokawa%E5%85%AC%E8%AA%8DMAD%E3%80%90%EF%BE%8D%EF%BE%9E%EF%BD%B0%EF%BD%BD%20%E6%BC%94%E5%A5%8F%E3%80%91",
  'https://www.youtube.com/watch?v=WWB01IuMvzA',
  '4:41'
]
localeString: Now playing [**Godhttps://www.youtube.com/watch?v=WWB01IuMvzA0knows...%20''The%20Melancholy%20of%20Haruhi%20Suzumiya''%20%E3%80%90%E6%B6%BC%E5%AE%AE%E3%83%8F%E3%83%AB%E3%83%92%E3%81%AE%E6%86%82%E9%AC%B1%E3%80%91Kadokawa%E5%85%AC%E8%AA%8DMAD%E3%80%90%EF%BE%8D%EF%BE%9E%EF%BD%B0%EF%BD%BD%20%E6%BC%94%E5%A5%8F%E3%80%91**](%2) `[4:41]`
2025-04-11T11:49:46.743Z  INFO  Quaver Shutting down due to unhandledRejection...
2025-04-11T11:49:46.744Z  INFO  Quaver Disconnecting from all guilds...
2025-04-11T11:49:46.744Z  INFO  Quaver [G 906471497231630336] Disconnecting (restarting)
Safe vars: []
localeString: Current
Safe vars: []
localeString: Queue
Safe vars: []
localeString: Quaver has crashed and will disconnect.
Safe vars: []
localeString: Your queue data has been attached.
Safe vars: []
localeString: Sorry for the inconvenience caused.
2025-04-11T11:49:48.781Z  ERROR  Quaver URI malformed
URIError: URI malformed
    at decodeURI (<anonymous>)
    at getLocaleString (file:///D:/Documents/GitHub/Quaver/dist/lib/util/util.js:35:12)
    at Object.execute (file:///D:/Documents/GitHub/Quaver/dist/events/music/trackStart.js:53:52)
2025-04-11T11:49:48.782Z  INFO  Quaver Logging additional output to error.log.
2025-04-11T11:49:49.062Z  WARN  Discord Disconnected.
PS D:\Documents\GitHub\Quaver>
```

**Review by xayanide — CHANGES_REQUESTED** [review]

File: src/lib/util/util.ts (hunk 1 above)
Comment (xayanide) [reply src/lib/util/util.ts]: Resolved in [fcf6b0a](https://github.com/ZPTXDev/Quaver/pull/1368/commits/fcf6b0a5d56dc18410b2be3be92134734d1e0fe0)

**Review by xayanide — APPROVED** [review]
