### PR TITLE
fix: do not set a "new pause timeout" if it exists

### LINKED ISSUE #350: Quaver sets a new pause timeout each time when moved to a new voice or stage channel
**Describe the bug**
What isn't working as intended, and what does it affect?
Affects functionality
User experience

**Severity**
- [x] Critical
- [ ] High
- [ ] Medium
- [ ] Low

**Affected versions**
What versions are affected by this bug? (e.g. >=3.0.1, 2.5.1-2.6.3, >=1.2.0)
`~2.8.0^`

**Steps to reproduce**
Steps to reproduce the behavior. (e.g. click on a button, enter a value, etc. and see error)
1. Play any track with Quaver with 24/7 disabled
2. Move Quaver to a voice or stage channel with no humans
2. Move Quaver to a voice or stagechannel with no humans again

**Expected behavior**
What is expected to happen?
Retain its previously set pause timeout and not set a new one when it is moved to a new voice or stage channel

**Actual behavior**
What actually happens? Attach or add errors or screenshots here as well.
Sets a new pause timeout each time it is moved to another channel

### PR DESCRIPTION
**Pull request by Xayanide**
### Thank you for your interest in contributing!
Before proceeding, please review the [guidelines for contributing](https://github.com/ZPTXDev/Quaver/blob/master/CONTRIBUTING.md).

- [x] Are you targeting the `next` branch? (right side)
- [x] Did you review the guidelines for contributing?
- [x] Does your code pass linting checks?
- [ ] Is your code documented, if applicable? (Check if not applicable)
- [x] Does this PR have a linked issue?

### Scope of change
- [ ] Major change
- [x] Minor change
- [ ] Documentation only

### Type of change
- [x] Bug fix
- [ ] Feature
- [ ] Other

### Priority
- [x] Critical
- [ ] High
- [ ] Medium
- [ ] Low

### Description
Please describe the changes.
Affects functionality
Fixes #350

Should not clear and set a new pauseTimeout if it already exists.
When setting a new pauseTimeout, clear any pauseTimeout at any cost even if it can be `undefined` at `/** Checks for when a user leaves */`

### CODE REVIEW

File: events/voiceStateUpdate.js [hunk 1]
```diff
@@ -95,9 +95,10 @@ module.exports = {
 				// Quaver was playing something - set pauseTimeout
 				await player.pause();
 				logger.info({ message: `[G ${player.guildId}] Setting pause timeout`, label: 'Quaver' });
-				if (player.pauseTimeout) {
-					clearTimeout(player.pauseTimeout);
-				}
+				// Ensure that the bot does not set a new pauseTimeout if pauseTimeout already exists
+				if (player.pauseTimeout) return;
+				// When setting a pauseTimeout, clear pauseTimeout at any cost as failsafe
+				clearTimeout(player.pauseTimeout);
```
Comment (Xayanide) [inline events/voiceStateUpdate.js:101]: `player.pauseTimeout` is always `undefined` here. Because everytime the user resumes its session, pauseTimeout gets cleared. This is a redundant statement and will for now stay here as a failsafe.

File: events/voiceStateUpdate.js [hunk 2]
```diff
@@ -152,9 +153,8 @@ module.exports = {
 		// Quaver was playing something - set pauseTimeout
 		await player.pause();
 		logger.info({ message: `[G ${player.guildId}] Setting pause timeout`, label: 'Quaver' });
-		if (player.pauseTimeout) {
-			clearTimeout(player.pauseTimeout);
-		}
+		// When setting a pauseTimeout, clear pauseTimeout at any cost as failsafe
+		clearTimeout(player.pauseTimeout);
```
Comment (Xayanide) [inline events/voiceStateUpdate.js:157]: `player.pauseTimeout` is always `undefined` here as well. This is a redundant statement and will for now stay here as a failsafe.

**Comment by Xayanide** [comment]
Normal use cases seem fine after testing.

**Review by zapteryx — APPROVED** [review]
