### PR TITLE
fix: destroy the player if timed out while queuing tracks

### LINKED ISSUE #385: Player is not destroyed if Quaver is timed out while queuing tracks
**Describe the bug**
What isn't working as intended, and what does it affect?
Affects functionality

**Severity**
- [x] Critical
- [ ] High
- [ ] Medium
- [ ] Low

**Affected versions**
What versions are affected by this bug? (e.g. >=3.0.1, 2.5.1-2.6.3, >=1.2.0)
`> 3.3.0`

**Steps to reproduce**
Steps to reproduce the behavior. (e.g. click on a button, enter a value, etc. and see error)
1. Queue any track with Quaver with play or search command in a voice or stage channel.
2. After queueing the tracks or sending the command, quickly time out Quaver on the spot.

**Expected behavior**
What is expected to happen?
Cancel the interaction, destroy the player.

**Actual behavior**
What actually happens? Attach or add errors or screenshots here as well.
There is no error.
Quaver didn't destroy the player when it got timed out. The player still exists while Quaver is nowhere to be found on any voice or stage channels.

Whenever the user uses commands that involves players. Quaver will say
`You have to be in my voice channel`

Basically Quaver thinks it is in a voice or stage channel when it is not.

### PR DESCRIPTION
**Pull request by Xayanide**
### Thank you for your interest in contributing!
Before proceeding, please review the [guidelines for contributing](https://github.com/ZPTXDev/Quaver/blob/master/CONTRIBUTING.md).

- [x] Are you targeting the `next` branch? (right side)
- [x] Did you review the guidelines for contributing?
- [x] Does your code pass linting checks?
- [ ] Is your code documented, if applicable? (Check if not applicable)
- [x] Does this PR have a linked issue?

### Scope of change
- [ ] Major change
- [x] Minor change
- [ ] Documentation only

### Type of change
- [x] Bug fix
- [ ] Feature
- [ ] Other

### Priority
- [x] Critical
- [ ] High
- [ ] Medium
- [ ] Low

### Description
Please describe the changes.
Fixes #385

Adds a check for when Quaver gets timed out while it is queueing tracks.
Updated the documentation accordingly.

Adds optional chaining operators for when `members` becomes `null` 

It is in one line together with the `// that kid left while we were busy` condition.

### CODE REVIEW

**Review by zapteryx — CHANGES_REQUESTED** [review]
I'd prefer that it specifically tells the user that Quaver had been timed out rather than using the interaction canceled message.

File: commands/play.js [hunk 1]
```diff
@@ -104,9 +104,12 @@ module.exports = {
...
 			await player.connect(interaction.member.voice.channelId, { deafened: true });
-			// that kid left while we were busy bruh
-			if (!interaction.member.voice.channelId) {
-				await interaction.replyHandler.locale('DISCORD_INTERACTION_CANCELED', {}, interaction.user.id);
+			// Ensure that Quaver destroys the player if the user leaves the channel while Quaver is queueing tracks
+			// Ensure that Quaver destroys the player if Quaver gets timed out by the user while Quaver is queueing tracks
+			const timedOut = interaction.guild?.members.me.isCommunicationDisabled();
+			if (!interaction.member.voice.channelId || timedOut) {
+				if (timedOut) await interaction.replyHandler.localeError('DISCORD_BOT_TIMED_OUT');
+				if (!timedOut) await interaction.replyHandler.locale('DISCORD_INTERACTION_CANCELED', {}, interaction.user.id);
```
Comment (zapteryx) [inline commands/play.js:112]: redundant `if (!timedOut)` condition

File: components/selects/play.js [hunk 2]
```diff
@@ -60,9 +60,12 @@ module.exports = {
...
 			await player.connect(interaction.member.voice.channelId, { deafened: true });
-			// that kid left while we were busy bruh
-			if (!interaction.member.voice.channelId) {
-				await interaction.replyHandler.locale('DISCORD_INTERACTION_CANCELED', { components: [] }, interaction.user.id);
+			// Ensure that Quaver destroys the player if the user leaves the channel while Quaver is queueing tracks
+			// Ensure that Quaver destroys the player if Quaver gets timed out by the user while Quaver is queueing tracks
+			const timedOut = interaction.guild?.members.me.isCommunicationDisabled();
+			if (!interaction.member.voice.channelId || timedOut) {
+				if (timedOut) await interaction.replyHandler.localeError('DISCORD_BOT_TIMED_OUT', { components: [] });
+				if (!timedOut) await interaction.replyHandler.locale('DISCORD_INTERACTION_CANCELED', { components: [] }, interaction.user.id);
```
Comment (zapteryx) [inline components/selects/play.js:68]: redundant `if (!timedOut)` condition

**Review by zapteryx — CHANGES_REQUESTED** [review]

File: commands/play.js (hunk 1 above)
Comment (Xayanide) [reply commands/play.js:112]: No it is not, for instance Quaver is timed out, it would only trigger `DISCORD_BOT_TIMED_OUT`, not including `DISCORD_INTERACTION_CANCELED`

Comment (Xayanide) [reply commands/play.js:112]: I will apply your suggestion unless if it gives an error.

**Comment by Xayanide** [comment]
With the latest changes (with the applied request changes) in this pr. Quaver sent the timed out message, but interaction cancelled locale went on top of it.
https://user-images.githubusercontent.com/18362871/179656795-d3c49703-a166-49d7-8d06-18a495d8a803.mp4

**Comment by zapteryx** [comment]
@Xayanide try the new changes

**Review by zapteryx — APPROVED** [review]

**Comment by Xayanide** [comment]
Seems fine, it is better.
