### PR TITLE
fix(voiceStateUpdate): do not set pause timeout if timeout exists

### LINKED ISSUE #356: Quaver sets pause timeout with no pending tracks and humans when the user consecutively skips the track and moves Quaver to another channel
**Describe the bug**
What isn't working as intended, and what does it affect?
Pause timeout
Affects functionality user experience
Is not reproducible with low latency.

**Severity**
- [x] Critical
- [ ] High
- [ ] Medium
- [ ] Low

**Affected versions**
What versions are affected by this bug? (e.g. >=3.0.1, 2.5.1-2.6.3, >=1.2.0)
3.4.2-next.3

**Steps to reproduce**
Steps to reproduce the behavior. (e.g. click on a button, enter a value, etc. and see error)
1. Play any track with Quaver in voice or stage channel
2. Type `/skip` do not enter it yet.
3. Move your cursor to Quaver on the voice or stage channel or any way that you can move Quaver quickly to another voice or stage channel
4. Prepare to enter skip then move Quaver to another voice or stage channel quickly.
5. Must be done in quick succession.

**Expected behavior**
What is expected to happen?
Do not set pause timeout

**Actual behavior**
What actually happens? Attach or add errors or screenshots here as well.
Sets a pause timeout while there are no tracks and humans at all

Related to the pauseTimeout Quartet issues:
#239
#346
#357

### PR DESCRIPTION
**Pull request by Xayanide**
### Thank you for your interest in contributing!
Before proceeding, please review the [guidelines for contributing](https://github.com/ZPTXDev/Quaver/blob/master/CONTRIBUTING.md).

- [x] Are you targeting the `next` branch? (right side)
- [x] Did you review the guidelines for contributing?
- [x] Does your code pass linting checks?
- [ ] Is your code documented, if applicable? (Check if not applicable)
- [x] Does this PR have a linked issue?

### Scope of change
- [ ] Major change
- [x] Minor change
- [ ] Documentation only

### Type of change
- [x] Bug fix
- [ ] Feature
- [ ] Other

### Priority
- [x] Critical
- [ ] High
- [ ] Medium
- [ ] Low

### Description
Please describe the changes.

Fixes #356
At `Checks for when Quaver moves`, should not set pause timeout if timeout already exists when moved.

### CODE REVIEW

File: events/voiceStateUpdate.js [hunk 1]
```diff
@@ -92,6 +92,8 @@ module.exports = {
 				}
 				// Avoid pauseTimeout if 24/7 is enabled
 				if (await data.guild.get(player.guildId, 'settings.stay.enabled')) return;
+				// Ensure that the bot does not set pauseTimeout if timeout already exists
+				if (player.timeout) return;
```
Comment (Xayanide) [inline events/voiceStateUpdate.js:96]: It is possible to put `player.timeout` and `player.pauseTimeout` checks in a single if statement. I will leave it at that for now.

**Review by zapteryx — CHANGES_REQUESTED** [review]
just put it in a single line `if (player.timeout || player.pauseTimeout) return;`

**Review by zapteryx — APPROVED** [review]
